import type { Song } from "@/lib/catalog";

// Generated by scripts/sync-catalog.mjs. Do not edit manually.
export const SUPPLEMENTAL_SONGS: Song[] = [
  {
    "slug": "catalog-1891010721",
    "title": "Dancing Heart La-Pa-Pa-Pa!",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891010718.jpg",
    "source": "https://music.apple.com/jp/album/dancing-heart-la-pa-pa-pa/1891010718?i=1891010721&uo=4"
  },
  {
    "slug": "catalog-1891010722",
    "title": "Dreaming Energy",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891010718.jpg",
    "source": "https://music.apple.com/jp/album/dreaming-energy/1891010718?i=1891010722&uo=4"
  },
  {
    "slug": "catalog-1822731405",
    "title": "私のSymphony",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822731402.jpg",
    "source": "https://music.apple.com/jp/album/%E7%A7%81%E3%81%AEsymphony/1822731402?i=1822731405&uo=4"
  },
  {
    "slug": "catalog-1891011689",
    "title": "だから僕らは鳴らすんだ!",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891011687.jpg",
    "source": "https://music.apple.com/jp/album/%E3%81%A0%E3%81%8B%E3%82%89%E5%83%95%E3%82%89%E3%81%AF%E9%B3%B4%E3%82%89%E3%81%99%E3%82%93%E3%81%A0/1891011687?i=1891011689&uo=4"
  },
  {
    "slug": "catalog-1891006901",
    "title": "この街でいまキミと",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891006898.jpg",
    "source": "https://music.apple.com/jp/album/%E3%81%93%E3%81%AE%E8%A1%97%E3%81%A7%E3%81%84%E3%81%BE%E3%82%AD%E3%83%9F%E3%81%A8/1891006898?i=1891006901&uo=4"
  },
  {
    "slug": "catalog-1891005862",
    "title": "1.2.3!",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891005858.jpg",
    "source": "https://music.apple.com/jp/album/1-2-3/1891005858?i=1891005862&uo=4"
  },
  {
    "slug": "catalog-1891006063",
    "title": "GOING UP",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891006058.jpg",
    "source": "https://music.apple.com/jp/album/going-up/1891006058?i=1891006063&uo=4"
  },
  {
    "slug": "catalog-1891006061",
    "title": "Tiny Stars",
    "bucket": "group",
    "artist": "澁谷かのん & 唐 可可",
    "cover": "/covers/catalog/1891006058.jpg",
    "source": "https://music.apple.com/jp/album/tiny-stars/1891006058?i=1891006061&uo=4"
  },
  {
    "slug": "catalog-1891005859",
    "title": "未来予報ハレルヤ!",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891005858.jpg",
    "source": "https://music.apple.com/jp/album/%E6%9C%AA%E6%9D%A5%E4%BA%88%E5%A0%B1%E3%83%8F%E3%83%AC%E3%83%AB%E3%83%A4/1891005858?i=1891005859&uo=4"
  },
  {
    "slug": "catalog-1891009207",
    "title": "Wish Song",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891009204.jpg",
    "source": "https://music.apple.com/jp/album/wish-song/1891009204?i=1891009207&uo=4"
  },
  {
    "slug": "catalog-1891008811",
    "title": "バイバイしちゃえば!?",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891008659.jpg",
    "source": "https://music.apple.com/jp/album/%E3%83%90%E3%82%A4%E3%83%90%E3%82%A4%E3%81%97%E3%81%A1%E3%82%83%E3%81%88%E3%81%B0/1891008659?i=1891008811&uo=4"
  },
  {
    "slug": "catalog-1891009210",
    "title": "瞬きの先へ",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891009204.jpg",
    "source": "https://music.apple.com/jp/album/%E7%9E%AC%E3%81%8D%E3%81%AE%E5%85%88%E3%81%B8/1891009204?i=1891009210&uo=4"
  },
  {
    "slug": "catalog-1891008663",
    "title": "常夏☆サンシャイン",
    "bucket": "group",
    "artist": "澁谷かのん, 唐 可可, 嵐 千砂都 & 平安名すみれ",
    "cover": "/covers/catalog/1891008659.jpg",
    "source": "https://music.apple.com/jp/album/%E5%B8%B8%E5%A4%8F-%E3%82%B5%E3%83%B3%E3%82%B7%E3%83%A3%E3%82%A4%E3%83%B3/1891008659?i=1891008663&uo=4"
  },
  {
    "slug": "catalog-1891009585",
    "title": "Day1",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891009582.jpg",
    "source": "https://music.apple.com/jp/album/day1/1891009582?i=1891009585&uo=4"
  },
  {
    "slug": "catalog-1891010507",
    "title": "Dream Rainbow",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891010504.jpg",
    "source": "https://music.apple.com/jp/album/dream-rainbow/1891010504?i=1891010507&uo=4"
  },
  {
    "slug": "catalog-1891009584",
    "title": "Starlight Prologue",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891009582.jpg",
    "source": "https://music.apple.com/jp/album/starlight-prologue/1891009582?i=1891009584&uo=4"
  },
  {
    "slug": "catalog-1891009583",
    "title": "ノンフィクション!!",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891009582.jpg",
    "source": "https://music.apple.com/jp/album/%E3%83%8E%E3%83%B3%E3%83%95%E3%82%A3%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3/1891009582?i=1891009583&uo=4"
  },
  {
    "slug": "catalog-1891324599",
    "title": "Departure",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891324402.jpg",
    "source": "https://music.apple.com/jp/album/departure/1891324402?i=1891324599&uo=4"
  },
  {
    "slug": "catalog-1891324404",
    "title": "Primary",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891324402.jpg",
    "source": "https://music.apple.com/jp/album/primary/1891324402?i=1891324404&uo=4"
  },
  {
    "slug": "catalog-1822719913",
    "title": "スター宣言",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822719909.jpg",
    "source": "https://music.apple.com/jp/album/%E3%82%B9%E3%82%BF%E3%83%BC%E5%AE%A3%E8%A8%80/1822719909?i=1822719913&uo=4"
  },
  {
    "slug": "catalog-1822720076",
    "title": "水しぶきのサイン",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822719774.jpg",
    "source": "https://music.apple.com/jp/album/%E6%B0%B4%E3%81%97%E3%81%B6%E3%81%8D%E3%81%AE%E3%82%B5%E3%82%A4%E3%83%B3/1822719774?i=1822720076&uo=4"
  },
  {
    "slug": "catalog-1822722799",
    "title": "Go!! リスタート",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822722796.jpg",
    "source": "https://music.apple.com/jp/album/go-%E3%83%AA%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88/1822722796?i=1822722799&uo=4"
  },
  {
    "slug": "catalog-1822723231",
    "title": "Welcome to 僕らのセカイ",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822723020.jpg",
    "source": "https://music.apple.com/jp/album/welcome-to-%E5%83%95%E3%82%89%E3%81%AE%E3%82%BB%E3%82%AB%E3%82%A4/1822723020?i=1822723231&uo=4"
  },
  {
    "slug": "catalog-1822722800",
    "title": "色づいて透明",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822722796.jpg",
    "source": "https://music.apple.com/jp/album/%E8%89%B2%E3%81%A5%E3%81%84%E3%81%A6%E9%80%8F%E6%98%8E/1822722796?i=1822722800&uo=4"
  },
  {
    "slug": "catalog-1822723233",
    "title": "揺らぐわ",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822723020.jpg",
    "source": "https://music.apple.com/jp/album/%E6%8F%BA%E3%82%89%E3%81%90%E3%82%8F/1822723020?i=1822723233&uo=4"
  },
  {
    "slug": "catalog-1822740020",
    "title": "Chance Day, Chance Way!",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822740018.jpg",
    "source": "https://music.apple.com/jp/album/chance-day-chance-way/1822740018?i=1822740020&uo=4"
  },
  {
    "slug": "catalog-1822744623",
    "title": "POP TALKING",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822744620.jpg",
    "source": "https://music.apple.com/jp/album/pop-talking/1822744620?i=1822744623&uo=4"
  },
  {
    "slug": "catalog-1822744621",
    "title": "ビタミンSUMMER!",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822744620.jpg",
    "source": "https://music.apple.com/jp/album/%E3%83%93%E3%82%BF%E3%83%9F%E3%83%B3summer/1822744620?i=1822744621&uo=4"
  },
  {
    "slug": "catalog-1822740022",
    "title": "ユートピアマジック",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822740018.jpg",
    "source": "https://music.apple.com/jp/album/%E3%83%A6%E3%83%BC%E3%83%88%E3%83%94%E3%82%A2%E3%83%9E%E3%82%B8%E3%83%83%E3%82%AF/1822740018?i=1822740022&uo=4"
  },
  {
    "slug": "catalog-1822746416",
    "title": "Sing!Shine!Smile!",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822746414.jpg",
    "source": "https://music.apple.com/jp/album/sing-shine-smile/1822746414?i=1822746416&uo=4"
  },
  {
    "slug": "catalog-1822746419",
    "title": "TO BE CONTINUED",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822746414.jpg",
    "source": "https://music.apple.com/jp/album/to-be-continued/1822746414?i=1822746419&uo=4"
  },
  {
    "slug": "catalog-1822745584",
    "title": "未来の音が聴こえる",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822745582.jpg",
    "source": "https://music.apple.com/jp/album/%E6%9C%AA%E6%9D%A5%E3%81%AE%E9%9F%B3%E3%81%8C%E8%81%B4%E3%81%93%E3%81%88%E3%82%8B/1822745582?i=1822745584&uo=4"
  },
  {
    "slug": "catalog-1822745585",
    "title": "名前呼びあうように",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822745582.jpg",
    "source": "https://music.apple.com/jp/album/%E5%90%8D%E5%89%8D%E5%91%BC%E3%81%B3%E3%81%82%E3%81%86%E3%82%88%E3%81%86%E3%81%AB/1822745582?i=1822745585&uo=4"
  },
  {
    "slug": "catalog-1822746968",
    "title": "Time to go",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822746950.jpg",
    "source": "https://music.apple.com/jp/album/time-to-go/1822746950?i=1822746968&uo=4"
  },
  {
    "slug": "catalog-1822746960",
    "title": "プライム・アドベンチャー",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1822746950.jpg",
    "source": "https://music.apple.com/jp/album/%E3%83%97%E3%83%A9%E3%82%A4%E3%83%A0-%E3%82%A2%E3%83%89%E3%83%99%E3%83%B3%E3%83%81%E3%83%A3%E3%83%BC/1822746950?i=1822746960&uo=4"
  },
  {
    "slug": "catalog-1765296996",
    "title": "MIRACLE NEW STORY",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1765296993.jpg",
    "source": "https://music.apple.com/jp/album/miracle-new-story/1765296993?i=1765296996&uo=4"
  },
  {
    "slug": "catalog-1765296998",
    "title": "キラーキューン☆",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1765296993.jpg",
    "source": "https://music.apple.com/jp/album/%E3%82%AD%E3%83%A9%E3%83%BC%E3%82%AD%E3%83%A5%E3%83%BC%E3%83%B3/1765296993?i=1765296998&uo=4"
  },
  {
    "slug": "catalog-1765314870",
    "title": "Jump Into the New World",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1765314869.jpg",
    "source": "https://music.apple.com/jp/album/jump-into-the-new-world/1765314869?i=1765314870&uo=4"
  },
  {
    "slug": "catalog-1765314185",
    "title": "UNIVERSE!!",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1765314184.jpg",
    "source": "https://music.apple.com/jp/album/universe/1765314184?i=1765314185&uo=4"
  },
  {
    "slug": "catalog-1719035298",
    "title": "FANTASTiC",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1719034965.jpg",
    "source": "https://music.apple.com/jp/album/fantastic/1719034965?i=1719035298&uo=4"
  },
  {
    "slug": "catalog-1719034966",
    "title": "シェキラ☆☆☆",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1719034965.jpg",
    "source": "https://music.apple.com/jp/album/%E3%82%B7%E3%82%A7%E3%82%AD%E3%83%A9/1719034965?i=1719034966&uo=4"
  },
  {
    "slug": "catalog-1719035299",
    "title": "私のSymphony (2023Ver.)",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1719034965.jpg",
    "source": "https://music.apple.com/jp/album/%E7%A7%81%E3%81%AEsymphony-2023ver/1719034965?i=1719035299&uo=4"
  },
  {
    "slug": "catalog-1755116236",
    "title": "アイコトバ!",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1755116233.jpg",
    "source": "https://music.apple.com/jp/album/%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%88%E3%83%90/1755116233?i=1755116236&uo=4"
  },
  {
    "slug": "catalog-1765309342",
    "title": "トゥトゥトゥ!",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1765309340.jpg",
    "source": "https://music.apple.com/jp/album/%E3%83%88%E3%82%A5%E3%83%88%E3%82%A5%E3%83%88%E3%82%A5/1765309340?i=1765309342&uo=4"
  },
  {
    "slug": "catalog-1765485944",
    "title": "HAPPY TO DO WA!",
    "bucket": "group",
    "artist": "唐 可可, 平安名すみれ & 葉月 恋",
    "cover": "/covers/catalog/1765485943.jpg",
    "source": "https://music.apple.com/jp/album/happy-to-do-wa/1765485943?i=1765485944&uo=4"
  },
  {
    "slug": "catalog-1765656825",
    "title": "Stella!",
    "bucket": "group",
    "artist": "澁谷かのん, 嵐 千砂都 & 平安名すみれ",
    "cover": "/covers/catalog/1765656824.jpg",
    "source": "https://music.apple.com/jp/album/stella/1765656824?i=1765656825&uo=4"
  },
  {
    "slug": "catalog-1765657173",
    "title": "クレッシェンドゆ・ら",
    "bucket": "group",
    "artist": "唐 可可 & 葉月 恋",
    "cover": "/covers/catalog/1765657172.jpg",
    "source": "https://music.apple.com/jp/album/%E3%82%AF%E3%83%AC%E3%83%83%E3%82%B7%E3%82%A7%E3%83%B3%E3%83%89%E3%82%86-%E3%82%89/1765657172?i=1765657173&uo=4"
  },
  {
    "slug": "catalog-1765657535",
    "title": "探して!Future",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1765657534.jpg",
    "source": "https://music.apple.com/jp/album/%E6%8E%A2%E3%81%97%E3%81%A6-future/1765657534?i=1765657535&uo=4"
  },
  {
    "slug": "catalog-1765657038",
    "title": "変わらないすべて",
    "bucket": "group",
    "artist": "澁谷かのん & 嵐 千砂都",
    "cover": "/covers/catalog/1765657037.jpg",
    "source": "https://music.apple.com/jp/album/%E5%A4%89%E3%82%8F%E3%82%89%E3%81%AA%E3%81%84%E3%81%99%E3%81%B9%E3%81%A6/1765657037?i=1765657038&uo=4"
  },
  {
    "slug": "catalog-1766467114",
    "title": "Blooming Dance!Dance!",
    "bucket": "group",
    "artist": "桜小路きな子, 米女メイ, 若菜四季 & 鬼塚夏美",
    "cover": "/covers/catalog/1766467113.jpg",
    "source": "https://music.apple.com/jp/album/blooming-dance-dance/1766467113?i=1766467114&uo=4"
  },
  {
    "slug": "catalog-1766466880",
    "title": "Hoshizora Monologue",
    "bucket": "group",
    "artist": "澁谷かのん, 唐 可可, 嵐 千砂都, 平安名すみれ & 葉月 恋",
    "cover": "/covers/catalog/1766466878.jpg",
    "source": "https://music.apple.com/jp/album/hoshizora-monologue/1766466878?i=1766466880&uo=4"
  },
  {
    "slug": "catalog-1766464753",
    "title": "Including you",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1766464750.jpg",
    "source": "https://music.apple.com/jp/album/including-you/1766464750?i=1766464753&uo=4"
  },
  {
    "slug": "catalog-1773460559",
    "title": "Bubble Rise",
    "bucket": "group",
    "artist": "澁谷かのん, ウィーン・マルガレーテ & 鬼塚冬毬",
    "cover": "/covers/catalog/1773460558.jpg",
    "source": "https://music.apple.com/jp/album/bubble-rise/1773460558?i=1773460559&uo=4"
  },
  {
    "slug": "catalog-1769353968",
    "title": "Within a Dream",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1769353965.jpg",
    "source": "https://music.apple.com/jp/album/within-a-dream/1769353965?i=1769353968&uo=4"
  },
  {
    "slug": "catalog-1769354047",
    "title": "青春HOPPERS",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1769354044.jpg",
    "source": "https://music.apple.com/jp/album/%E9%9D%92%E6%98%A5hoppers/1769354044?i=1769354047&uo=4"
  },
  {
    "slug": "catalog-1773460560",
    "title": "Special Color",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1773460558.jpg",
    "source": "https://music.apple.com/jp/album/special-color/1773460558?i=1773460560&uo=4"
  },
  {
    "slug": "catalog-1773460561",
    "title": "いつものピースサイン",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1773460558.jpg",
    "source": "https://music.apple.com/jp/album/%E3%81%84%E3%81%A4%E3%82%82%E3%81%AE%E3%83%94%E3%83%BC%E3%82%B9%E3%82%B5%E3%82%A4%E3%83%B3/1773460558?i=1773460561&uo=4"
  },
  {
    "slug": "catalog-1773460280",
    "title": "ファイティングコール",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1773459917.jpg",
    "source": "https://music.apple.com/jp/album/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E3%82%B3%E3%83%BC%E3%83%AB/1773459917?i=1773460280&uo=4"
  },
  {
    "slug": "catalog-1779627813",
    "title": "絶対的LOVER",
    "bucket": "group",
    "artist": "Liella!, 澁谷かのん, ウィーン・マルガレーテ & 鬼塚冬毬",
    "cover": "/covers/catalog/1779627811.jpg",
    "source": "https://music.apple.com/jp/album/%E7%B5%B6%E5%AF%BE%E7%9A%84lover/1779627811?i=1779627813&uo=4"
  },
  {
    "slug": "catalog-1779627876",
    "title": "Dazzling Game",
    "bucket": "group",
    "artist": "Liella!, 澁谷かのん, ウィーン・マルガレーテ & 鬼塚冬毬",
    "cover": "/covers/catalog/1779627873.jpg",
    "source": "https://music.apple.com/jp/album/dazzling-game/1779627873?i=1779627876&uo=4"
  },
  {
    "slug": "catalog-1779627877",
    "title": "QUESTION99",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1779627873.jpg",
    "source": "https://music.apple.com/jp/album/question99/1779627873?i=1779627877&uo=4"
  },
  {
    "slug": "catalog-1779627817",
    "title": "真っ赤。",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1779627811.jpg",
    "source": "https://music.apple.com/jp/album/%E7%9C%9F%E3%81%A3%E8%B5%A4/1779627811?i=1779627817&uo=4"
  },
  {
    "slug": "catalog-1783510725",
    "title": "笑顔のPromise",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1783510724.jpg",
    "source": "https://music.apple.com/jp/album/%E7%AC%91%E9%A1%94%E3%81%AEpromise/1783510724?i=1783510725&uo=4"
  },
  {
    "slug": "catalog-1783510597",
    "title": "スーパースター!!",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1783510595.jpg",
    "source": "https://music.apple.com/jp/album/%E3%82%B9%E3%83%BC%E3%83%91%E3%83%BC%E3%82%B9%E3%82%BF%E3%83%BC/1783510595?i=1783510597&uo=4"
  },
  {
    "slug": "catalog-1783510598",
    "title": "Wish Song ～11 Ver.～",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1783510595.jpg",
    "source": "https://music.apple.com/jp/album/wish-song-11-ver/1783510595?i=1783510598&uo=4"
  },
  {
    "slug": "catalog-1783511001",
    "title": "君・街・空・星",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1783510724.jpg",
    "source": "https://music.apple.com/jp/album/%E5%90%9B-%E8%A1%97-%E7%A9%BA-%E6%98%9F/1783510724?i=1783511001&uo=4"
  },
  {
    "slug": "catalog-1784616304",
    "title": "始まりは君の空 ～11 Ver.～",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1784616302.jpg",
    "source": "https://music.apple.com/jp/album/%E5%A7%8B%E3%81%BE%E3%82%8A%E3%81%AF%E5%90%9B%E3%81%AE%E7%A9%BA-11-ver/1784616302?i=1784616304&uo=4"
  },
  {
    "slug": "catalog-1787242340",
    "title": "11th moon",
    "bucket": "group",
    "artist": "ウィーン・マルガレーテ & 鬼塚冬毬",
    "cover": "/covers/catalog/1787242096.jpg",
    "source": "https://music.apple.com/jp/album/11th-moon/1787242096?i=1787242340&uo=4"
  },
  {
    "slug": "catalog-1787242339",
    "title": "Summer Escape!!",
    "bucket": "group",
    "artist": "桜小路きな子, 米女メイ, 若菜四季 & 鬼塚夏美",
    "cover": "/covers/catalog/1787242096.jpg",
    "source": "https://music.apple.com/jp/album/summer-escape/1787242096?i=1787242339&uo=4"
  },
  {
    "slug": "catalog-1787242341",
    "title": "ひとひらだけ",
    "bucket": "group",
    "artist": "澁谷かのん, 唐 可可, 嵐 千砂都, 平安名すみれ & 葉月 恋",
    "cover": "/covers/catalog/1787242096.jpg",
    "source": "https://music.apple.com/jp/album/%E3%81%B2%E3%81%A8%E3%81%B2%E3%82%89%E3%81%A0%E3%81%91/1787242096?i=1787242341&uo=4"
  },
  {
    "slug": "catalog-1787242342",
    "title": "結ぶメロディ",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1787242096.jpg",
    "source": "https://music.apple.com/jp/album/%E7%B5%90%E3%81%B6%E3%83%A1%E3%83%AD%E3%83%87%E3%82%A3/1787242096?i=1787242342&uo=4"
  },
  {
    "slug": "catalog-1825102106",
    "title": "オレンジのままで",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1825102105.jpg",
    "source": "https://music.apple.com/jp/album/%E3%82%AA%E3%83%AC%E3%83%B3%E3%82%B8%E3%81%AE%E3%81%BE%E3%81%BE%E3%81%A7/1825102105?i=1825102106&uo=4"
  },
  {
    "slug": "catalog-1843565925",
    "title": "High!モチベーション",
    "bucket": "group",
    "artist": "桜小路きな子, 米女メイ, 若菜四季, 鬼塚夏美, ウィーン・マルガレーテ & 鬼塚冬毬",
    "cover": "/covers/catalog/1843565918.jpg",
    "source": "https://music.apple.com/jp/album/high-%E3%83%A2%E3%83%81%E3%83%99%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3/1843565918?i=1843565925&uo=4"
  },
  {
    "slug": "catalog-1843565921",
    "title": "OPEN THE G☆TE!!!",
    "bucket": "group",
    "artist": "Liella!",
    "cover": "/covers/catalog/1843565918.jpg",
    "source": "https://music.apple.com/jp/album/open-the-g-te/1843565918?i=1843565921&uo=4"
  },
  {
    "slug": "catalog-1891029909",
    "title": "LIVE with a smile! (Liella! Ver.)",
    "bucket": "others",
    "artist": "Liella!",
    "cover": "/covers/catalog/1891029905.jpg",
    "source": "https://music.apple.com/jp/album/live-with-a-smile-liella-ver/1891029905?i=1891029909&uo=4"
  },
  {
    "slug": "catalog-1891324408",
    "title": "Anniversary (唐 可可 Ver.)",
    "bucket": "solo",
    "artist": "唐 可可",
    "cover": "/covers/catalog/1891324402.jpg",
    "source": "https://music.apple.com/jp/album/anniversary-%E5%94%90-%E5%8F%AF%E5%8F%AF-ver/1891324402?i=1891324408&uo=4"
  },
  {
    "slug": "catalog-1891324589",
    "title": "Anniversary (葉月 恋 Ver.)",
    "bucket": "solo",
    "artist": "葉月 恋",
    "cover": "/covers/catalog/1891324402.jpg",
    "source": "https://music.apple.com/jp/album/anniversary-%E8%91%89%E6%9C%88-%E6%81%8B-ver/1891324402?i=1891324589&uo=4"
  },
  {
    "slug": "catalog-1891324598",
    "title": "Dears (平安名すみれ Ver.)",
    "bucket": "solo",
    "artist": "平安名すみれ",
    "cover": "/covers/catalog/1891324402.jpg",
    "source": "https://music.apple.com/jp/album/dears-%E5%B9%B3%E5%AE%89%E5%90%8D%E3%81%99%E3%81%BF%E3%82%8C-ver/1891324402?i=1891324598&uo=4"
  },
  {
    "slug": "catalog-1891324597",
    "title": "Dears (葉月 恋 Ver.)",
    "bucket": "solo",
    "artist": "葉月 恋",
    "cover": "/covers/catalog/1891324402.jpg",
    "source": "https://music.apple.com/jp/album/dears-%E8%91%89%E6%9C%88-%E6%81%8B-ver/1891324402?i=1891324597&uo=4"
  },
  {
    "slug": "catalog-1891324407",
    "title": "Memories (嵐 千砂都 Ver.)",
    "bucket": "solo",
    "artist": "嵐 千砂都",
    "cover": "/covers/catalog/1891324402.jpg",
    "source": "https://music.apple.com/jp/album/memories-%E5%B5%90-%E5%8D%83%E7%A0%82%E9%83%BD-ver/1891324402?i=1891324407&uo=4"
  },
  {
    "slug": "catalog-1891324406",
    "title": "Memories (澁谷かのん Ver.)",
    "bucket": "solo",
    "artist": "澁谷かのん",
    "cover": "/covers/catalog/1891324402.jpg",
    "source": "https://music.apple.com/jp/album/memories-%E6%BE%81%E8%B0%B7%E3%81%8B%E3%81%AE%E3%82%93-ver/1891324402?i=1891324406&uo=4"
  },
  {
    "slug": "catalog-1891324590",
    "title": "Message (平安名すみれ Ver.)",
    "bucket": "solo",
    "artist": "平安名すみれ",
    "cover": "/covers/catalog/1891324402.jpg",
    "source": "https://music.apple.com/jp/album/message-%E5%B9%B3%E5%AE%89%E5%90%8D%E3%81%99%E3%81%BF%E3%82%8C-ver/1891324402?i=1891324590&uo=4"
  },
  {
    "slug": "catalog-1891324592",
    "title": "Message (澁谷かのん Ver.)",
    "bucket": "solo",
    "artist": "澁谷かのん",
    "cover": "/covers/catalog/1891324402.jpg",
    "source": "https://music.apple.com/jp/album/message-%E6%BE%81%E8%B0%B7%E3%81%8B%E3%81%AE%E3%82%93-ver/1891324402?i=1891324592&uo=4"
  },
  {
    "slug": "catalog-1891324595",
    "title": "Ringing! (唐 可可 Ver.)",
    "bucket": "solo",
    "artist": "唐 可可",
    "cover": "/covers/catalog/1891324402.jpg",
    "source": "https://music.apple.com/jp/album/ringing-%E5%94%90-%E5%8F%AF%E5%8F%AF-ver/1891324402?i=1891324595&uo=4"
  },
  {
    "slug": "catalog-1891324594",
    "title": "Ringing! (嵐 千砂都 Ver.)",
    "bucket": "solo",
    "artist": "嵐 千砂都",
    "cover": "/covers/catalog/1891324402.jpg",
    "source": "https://music.apple.com/jp/album/ringing-%E5%B5%90-%E5%8D%83%E7%A0%82%E9%83%BD-ver/1891324402?i=1891324594&uo=4"
  },
  {
    "slug": "catalog-1891344899",
    "title": "ほんのちょっぴり ～Orchestra Ver.～",
    "bucket": "solo",
    "artist": "澁谷かのん",
    "cover": "/covers/catalog/1891344896.jpg",
    "source": "https://music.apple.com/jp/album/%E3%81%BB%E3%82%93%E3%81%AE%E3%81%A1%E3%82%87%E3%81%A3%E3%81%B4%E3%82%8A-orchestra-ver/1891344896?i=1891344899&uo=4"
  },
  {
    "slug": "catalog-1822746952",
    "title": "Dreamer Coaster (桜小路きな子 Ver.)",
    "bucket": "solo",
    "artist": "桜小路きな子",
    "cover": "/covers/catalog/1822746950.jpg",
    "source": "https://music.apple.com/jp/album/dreamer-coaster-%E6%A1%9C%E5%B0%8F%E8%B7%AF%E3%81%8D%E3%81%AA%E5%AD%90-ver/1822746950?i=1822746952&uo=4"
  },
  {
    "slug": "catalog-1822746951",
    "title": "Dreamer Coaster (澁谷かのん Ver.)",
    "bucket": "solo",
    "artist": "澁谷かのん",
    "cover": "/covers/catalog/1822746950.jpg",
    "source": "https://music.apple.com/jp/album/dreamer-coaster-%E6%BE%81%E8%B0%B7%E3%81%8B%E3%81%AE%E3%82%93-ver/1822746950?i=1822746951&uo=4"
  },
  {
    "slug": "catalog-1822746955",
    "title": "エンドレスサーキット (唐 可可 Ver.)",
    "bucket": "solo",
    "artist": "唐 可可",
    "cover": "/covers/catalog/1822746950.jpg",
    "source": "https://music.apple.com/jp/album/%E3%82%A8%E3%83%B3%E3%83%89%E3%83%AC%E3%82%B9%E3%82%B5%E3%83%BC%E3%82%AD%E3%83%83%E3%83%88-%E5%94%90-%E5%8F%AF%E5%8F%AF-ver/1822746950?i=1822746955&uo=4"
  },
  {
    "slug": "catalog-1822746956",
    "title": "エンドレスサーキット (平安名すみれ Ver.)",
    "bucket": "solo",
    "artist": "平安名すみれ",
    "cover": "/covers/catalog/1822746950.jpg",
    "source": "https://music.apple.com/jp/album/%E3%82%A8%E3%83%B3%E3%83%89%E3%83%AC%E3%82%B9%E3%82%B5%E3%83%BC%E3%82%AD%E3%83%83%E3%83%88-%E5%B9%B3%E5%AE%89%E5%90%8D%E3%81%99%E3%81%BF%E3%82%8C-ver/1822746950?i=1822746956&uo=4"
  },
  {
    "slug": "catalog-1822746962",
    "title": "パレードはいつも (若菜四季 Ver.)",
    "bucket": "solo",
    "artist": "若菜四季",
    "cover": "/covers/catalog/1822746950.jpg",
    "source": "https://music.apple.com/jp/album/%E3%83%91%E3%83%AC%E3%83%BC%E3%83%89%E3%81%AF%E3%81%84%E3%81%A4%E3%82%82-%E8%8B%A5%E8%8F%9C%E5%9B%9B%E5%AD%A3-ver/1822746950?i=1822746962&uo=4"
  },
  {
    "slug": "catalog-1822746961",
    "title": "パレードはいつも (米女メイ Ver.)",
    "bucket": "solo",
    "artist": "米女メイ",
    "cover": "/covers/catalog/1822746950.jpg",
    "source": "https://music.apple.com/jp/album/%E3%83%91%E3%83%AC%E3%83%BC%E3%83%89%E3%81%AF%E3%81%84%E3%81%A4%E3%82%82-%E7%B1%B3%E5%A5%B3%E3%83%A1%E3%82%A4-ver/1822746950?i=1822746961&uo=4"
  },
  {
    "slug": "catalog-1822746963",
    "title": "駆けるメリーゴーランド (嵐 千砂都 Ver.)",
    "bucket": "solo",
    "artist": "嵐 千砂都",
    "cover": "/covers/catalog/1822746950.jpg",
    "source": "https://music.apple.com/jp/album/%E9%A7%86%E3%81%91%E3%82%8B%E3%83%A1%E3%83%AA%E3%83%BC%E3%82%B4%E3%83%BC%E3%83%A9%E3%83%B3%E3%83%89-%E5%B5%90-%E5%8D%83%E7%A0%82%E9%83%BD-ver/1822746950?i=1822746963&uo=4"
  },
  {
    "slug": "catalog-1822746964",
    "title": "駆けるメリーゴーランド (澁谷かのん Ver.)",
    "bucket": "solo",
    "artist": "澁谷かのん",
    "cover": "/covers/catalog/1822746950.jpg",
    "source": "https://music.apple.com/jp/album/%E9%A7%86%E3%81%91%E3%82%8B%E3%83%A1%E3%83%AA%E3%83%BC%E3%82%B4%E3%83%BC%E3%83%A9%E3%83%B3%E3%83%89-%E6%BE%81%E8%B0%B7%E3%81%8B%E3%81%AE%E3%82%93-ver/1822746950?i=1822746964&uo=4"
  },
  {
    "slug": "catalog-1822746959",
    "title": "迷宮讃歌 (鬼塚夏美 Ver.)",
    "bucket": "solo",
    "artist": "鬼塚夏美",
    "cover": "/covers/catalog/1822746950.jpg",
    "source": "https://music.apple.com/jp/album/%E8%BF%B7%E5%AE%AE%E8%AE%83%E6%AD%8C-%E9%AC%BC%E5%A1%9A%E5%A4%8F%E7%BE%8E-ver/1822746950?i=1822746959&uo=4"
  },
  {
    "slug": "catalog-1822746958",
    "title": "迷宮讃歌 (葉月 恋 Ver.)",
    "bucket": "solo",
    "artist": "葉月 恋",
    "cover": "/covers/catalog/1822746950.jpg",
    "source": "https://music.apple.com/jp/album/%E8%BF%B7%E5%AE%AE%E8%AE%83%E6%AD%8C-%E8%91%89%E6%9C%88-%E6%81%8B-ver/1822746950?i=1822746958&uo=4"
  },
  {
    "slug": "catalog-1822748002",
    "title": "Butterfly Wing",
    "bucket": "solo",
    "artist": "ウィーン・マルガレーテ",
    "cover": "/covers/catalog/1822748001.jpg",
    "source": "https://music.apple.com/jp/album/butterfly-wing/1822748001?i=1822748002&uo=4"
  },
  {
    "slug": "catalog-1822748003",
    "title": "エーデルシュタイン",
    "bucket": "solo",
    "artist": "ウィーン・マルガレーテ",
    "cover": "/covers/catalog/1822748001.jpg",
    "source": "https://music.apple.com/jp/album/%E3%82%A8%E3%83%BC%E3%83%87%E3%83%AB%E3%82%B7%E3%83%A5%E3%82%BF%E3%82%A4%E3%83%B3/1822748001?i=1822748003&uo=4"
  },
  {
    "slug": "catalog-1765309648",
    "title": "Oh!レディ・ステディ・ポジティブ",
    "bucket": "solo",
    "artist": "唐 可可",
    "cover": "/covers/catalog/1765309646.jpg",
    "source": "https://music.apple.com/jp/album/oh-%E3%83%AC%E3%83%87%E3%82%A3-%E3%82%B9%E3%83%86%E3%83%87%E3%82%A3-%E3%83%9D%E3%82%B8%E3%83%86%E3%82%A3%E3%83%96/1765309646?i=1765309648&uo=4"
  },
  {
    "slug": "catalog-1765314528",
    "title": "ヒロインズ☆ランウェイ",
    "bucket": "solo",
    "artist": "平安名すみれ",
    "cover": "/covers/catalog/1765314527.jpg",
    "source": "https://music.apple.com/jp/album/%E3%83%92%E3%83%AD%E3%82%A4%E3%83%B3%E3%82%BA-%E3%83%A9%E3%83%B3%E3%82%A6%E3%82%A7%E3%82%A4/1765314527?i=1765314528&uo=4"
  },
  {
    "slug": "catalog-1765309150",
    "title": "リバーブ",
    "bucket": "solo",
    "artist": "葉月 恋",
    "cover": "/covers/catalog/1765309143.jpg",
    "source": "https://music.apple.com/jp/album/%E3%83%AA%E3%83%90%E3%83%BC%E3%83%96/1765309143?i=1765309150&uo=4"
  },
  {
    "slug": "catalog-1765309703",
    "title": "心キラララ",
    "bucket": "solo",
    "artist": "澁谷かのん",
    "cover": "/covers/catalog/1765309702.jpg",
    "source": "https://music.apple.com/jp/album/%E5%BF%83%E3%82%AD%E3%83%A9%E3%83%A9%E3%83%A9/1765309702?i=1765309703&uo=4"
  },
  {
    "slug": "catalog-1765309149",
    "title": "勇気のカケラ",
    "bucket": "solo",
    "artist": "嵐 千砂都",
    "cover": "/covers/catalog/1765309145.jpg",
    "source": "https://music.apple.com/jp/album/%E5%8B%87%E6%B0%97%E3%81%AE%E3%82%AB%E3%82%B1%E3%83%A9/1765309145?i=1765309149&uo=4"
  },
  {
    "slug": "catalog-1788857444",
    "title": "あふれる言葉",
    "bucket": "solo",
    "artist": "桜小路きな子",
    "cover": "/covers/catalog/1788857422.jpg",
    "source": "https://music.apple.com/jp/album/%E3%81%82%E3%81%B5%E3%82%8C%E3%82%8B%E8%A8%80%E8%91%89/1788857422?i=1788857444&uo=4"
  }
];
